services:
  - type: web
    name: telegram-questionnaire-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_PATH
        value: ./questionnaire.db
      - key: DB_USERNAME
        value: ""
      - key: DB_PASSWORD
        value: ""
      - key: WEBHOOK_URL
        sync: false
